sudo: required
language: generic
addons:
  apt:
    packages:
      - docker-ce
services:
        - docker
before_script:
        - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
        - sudo sed -i "s/{/{"experimental": true,/" /etc/docker/daemon.json
        - docker restart
script:
        - ./run.sh
        - docker version
        - sudo cat /etc/docker/daemon.json
        
