stages:
        - building
sudo: required
language: generic
dist: xenial
# Only build tags
#if: tag IS present
jobs:
  include:
        - stage: building

          install:
          - sudo apt-get update
          - sudo apt-get -y install linux-headers-$(uname -r)
          - sudo apt-get -y install virtualbox
          - sudo apt-get -y install vagrant

          script:
          - vagrant up
          - VBoxManage --version

notifications:
  email: false
