stages:
        - building_images
        - deploy
sudo: required
language: generic
dist: xenial
jobs:
  include:
        - stage: building_images
          script:
          - ./.travis/configure_docker.sh
          - ./docker-build.sh x86
          - docker images
notifications:
        email: false
