stages:
        - configuration
        - build_debian-ncp
        - build_lamp
        - build_nc
        - build_ncp
sudo: required
language: generic
addons:
  apt:
    packages:
        - docker-ce #Upgrade Docker to 18.06 version that supports experimental features
services:
        - docker
jobs:
   include:
        
        - stage: configuration
          env: null
          script: ./.travis/main.sh #configuration script for travis machine

        - stage: build_debian-ncp
          env: 
                TEST_SUITE=".travis/build-docker_test.sh x86"
                TEST_SUITE="ls"
          script: while sleep 9m; do echo "=====[ $SECONDS seconds, build-docker still building... ]====="; done & ./${TEST_SUITE} > output
