stages:
        - building_images
        - deploy
sudo: required
language: generic
dist: xenial
addons:
        firefox: latest
jobs:
  include:
        - stage: building_images
          script:
           - IP=$(ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')
           - ./.travis/configure_webtesting.sh
        - stage: deploy
          script: ls

notifications:
        email: false
