stages:
        - building
sudo: required
language: generic
dist: xenial
on tags: true
jobs:
  include:
        - stage: building

          install:
          - ./.travis/configure_docker.sh
          - sudo apt-get install vagrant
          - sudo apt-get install -q virtualbox --fix-missing
          - docker pull skandyla/travis-cli
          - docker tag skandyla/travis-cli travis-cli
          - travis login
          - ./.travis/travis-cli.sh status

          script:
          - vagrant up
          - curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash

notifications:
  email: false
