sudo: required
language: generic
addons:
  apt:
    packages:
      - docker-ce #Upgrade Docker to 18.06 version that supports experimental features
services:
        - docker
before_script:
        - ./.travis/main.sh #configuration script for travis machine
script:
        - docker version
        - sudo cat /etc/docker/daemon.json
        
