stages:
        - building_images
        - deploy
sudo: required
language: generic
dist: xenial
jobs:
  include:
        - stage: building_images
          script:
          - ./.travis/configure_docker.sh
          - export DOCKER_CLI_EXPERIMENTAL=enabled #enable experimental features
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker manifest create $DOCKER_USERNAME/nextcloudpi
          - docker images
notifications:
        email: false
