stages:
        - build_1
        - build_2
sudo: required
language: generic
before_script:
        - ./.travis/main.sh
        - export DOCKER_CLI_EXPERIMENTAL=enabled
cache:
   directories:
        - docker
jobs:
   include:
        - stage: build_1
          script:
                  - docker version
                  - printenv | grep DOCKER
                  - DOCKER_BUILDKIT=1 docker build . -f docker/debian-ncp/Dockerfile -t ownyourbits/debian-ncp-amd64:latest --pull --build-arg arch=amd64 --build-arg arch_qemu=x86_64 > output
                  - docker save ownyourbits/debian-ncp-amd64:latest | gzip -c > docker/debian-ncp.tar.gz
        - stage: build_2
          script:
                  - gzip -dc docker/debian-ncp.tar.gz | docker load
                  - sed -i "/innodb_file_format=barracuda/a open_files_limit=65536" lamp.sh
                  - while sleep 9m; do echo "=====[ $SECONDS seconds, build-docker still building... ]====="; done & DOCKER_BUILDKIT=1 docker build . -f docker/lamp/Dockerfile -t ownyourbits/lamp-amd64:latest --build-arg arch=amd64 > output
                  - docker images
                  - sed -i '/open_files_limit=65536/d' lamp.sh

notifications:
        email: false

