stages:
        - building
        - testing
        - release
sudo: required
language: generic
dist: xenial
branches:
  only:
        - gsoc2019-travis
cache:
  directories:
        - docker_cached
jobs:
  include:
        - stage: building

          ### x86 Docker images
          install:
          - ./.travis/configure_docker.sh #upgrading docker
          - export DOCKER_CLI_EXPERIMENTAL=enabled #enable experimental features
          - docker version #Check Docker 18.09 is installed

          script:
          - while sleep 9m; do echo "=====[ $SECONDS seconds, build-docker still building... ]====="; done & 
          - DOCKER_BUILDKIT=1 docker build . -f docker/debian-ncp/Dockerfile -t ownyourbits/debian-ncp-amd64:latest --pull --build-arg arch=amd64 --build-arg arch_qemu=x86_64 > output
          - sed -i "/innodb_file_format=barracuda/a open_files_limit=65536" lamp.sh
          - DOCKER_BUILDKIT=1 docker build . -f docker/lamp/Dockerfile -t ownyourbits/lamp-amd64:latest --build-arg arch=amd64 > output
          - sed -i '/open_files_limit=65536/d' lamp.sh
          - DOCKER_BUILDKIT=1 docker build . -f docker/nextcloud/Dockerfile -t ownyourbits/nextcloud-amd64:latest --build-arg arch=amd64 > output
          - DOCKER_BUILDKIT=1 docker build . -f docker/nextcloudpi/Dockerfile -t ownyourbits/nextcloudpi-amd64:latest --build-arg arch=amd64 > output
          - docker save ownyourbits/debian-ncp-amd64:latest > docker_cached/debian-ncp-amd64.tar
          - docker save ownyourbits/lamp-amd64:latest > docker_cached/lamp-amd64.tar
          - docker save ownyourbits/nextcloud-amd64:latest > docker_cached/nextcloud-amd64.tar
          - docker save ownyourbits/nextcloudpi-amd64:latest > docker_cached/nextcloudpi-amd64.tar

        - 
          ### armhf Docker images
          install:
          - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
          - ./.travis/configure_docker.sh #upgrading docker and installing packages for arm architecture
          - export DOCKER_CLI_EXPERIMENTAL=enabled #enable experimental features
          - docker version #Check Docker 18.09 is installed

          script: 
          - while sleep 9m; do echo "=====[ $SECONDS seconds, build-docker still building... ]====="; done &
          - DOCKER_BUILDKIT=1 docker build . -f docker/debian-ncp/Dockerfile -t ownyourbits/debian-ncp-armhf:latest --pull --build-arg arch=armhf --build-arg arch_qemu=arm > output
          - sed -i "/innodb_file_format=barracuda/a open_files_limit=65536" lamp.sh
          - DOCKER_BUILDKIT=1 docker build . -f docker/lamp/Dockerfile -t ownyourbits/lamp-armhf:latest --build-arg arch=armhf > output
          - sed -i '/open_files_limit=65536/d' lamp.sh
          - DOCKER_BUILDKIT=1 docker build . -f docker/nextcloud/Dockerfile -t ownyourbits/nextcloud-armhf:latest --build-arg arch=armhf > output
          - DOCKER_BUILDKIT=1 docker build . -f docker/nextcloudpi/Dockerfile -t ownyourbits/nextcloudpi-armhf:latest --build-arg arch=armhf > output
          - docker save ownyourbits/debian-nxp-armhf:latest > docker_cached/debian-ncp-armhf.tar
          - docker save ownyourbits/lamp-armhf:latest > docker_cached/lamp-armhf.tar
 	  - docker save ownyourbits/nextcloud-armhf:latest > docker_cached/nextcloud-armhf.tar
          - docker save ownyourbits/nextcloudpi-armhf:latest > docker_cached/nextcloudpi-armhf.tar

        -
          ### arm64 Docker images
          install:
          - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
          - ./.travis/configure_docker.sh #upgrading docker and installing packages for arm architecture
          - export DOCKER_CLI_EXPERIMENTAL=enabled #enable experimental features
          - docker version #Check Docker 18.09 is installed

          script:
          - while sleep 9m; do echo "=====[ $SECONDS seconds, build-docker still building... ]====="; done &
          - DOCKER_BUILDKIT=1 docker build . -f docker/debian-ncp/Dockerfile -t ownyourbits/debian-ncp-arm64v8:latest --build-arg arch=arm64v8 --build-arg arch_qemu=aarch64 > output
          - sed -i "/innodb_file_format=barracuda/a open_files_limit=65536" lamp.sh
          - DOCKER_BUILDKIT=1 docker build . -f docker/lamp/Dockerfile -t ownyourbits/lamp-arm64v8:latest --build-arg arch=arm64v8 > output
          - sed -i '/open_files_limit=65536/d' lamp.sh
	  - DOCKER_BUILDKIT=1 docker build . -f docker/nextcloud/Dockerfile -t ownyourbits/nextcloud-arm64v8:latest --build-arg arch=arm64v8 > output
          - DOCKER_BUILDKIT=1 docker build . -f docker/nextcloudpi/Dockerfile -t ownyourbits/nextcloudpi-arm64v8:latest --build-arg arch=arm64v8 > output
          - docker save ownyourbits/debian-ncp-arm64v8:latest > docker_cached/debian-ncp-arm64v8.tar
          - docker save ownyourbits/lamp-arm64v8:latest > docker_cached/lamp-arm64v8.tar
	  - docker save ownyourbits/nextcloud-arm64v8:latest > docker_cached/nextcloud-arm64v8.tar
          - docker save ownyourbits/nextcloudpi-arm64v8:latest > docker_cached/nextcloudpi-arm64v8.tar

notifications:
  email: false
