stages:
        - building
sudo: required
language: generic
dist: xenial
jobs:
  include:
        - stage: building

          install:
          - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
         
          script:
          - git clone https://github.com/eellak/gsoc2019-NextCloudPi.git
          - git checkout gsoc2019-travis
          - cd gsoc2019-NextCloudPi
          - sed -i "s/create_torrent/#create_torrent/" build-SD-rpi.sh
          - sed -i "s/upload_ftp/#upload_ftp/" build-SD-rpi.sh
          - sed -i "18s, ,echo gets-up-to-here," post-inst.sh
          - sed -i "23s, ,echo gets-up-to-here," post-inst.sh
          - sed -i "29s, ,echo gets-up-to-here," post-inst.sh
          - sed -i "87s, ,echo PREPACKING," build-SD-rpi.sh
          - while sleep 9m; do echo "=====[ $SECONDS seconds, still building rpi image... ]====="; done &
          - tail -f f_out &
          - ./build-SD-rpi.sh > f_out

notifications:
  email: false
