stages:
        - building
sudo: required
language: generic
dist: xenial
jobs:
  include:
        - stage: building

          install:
          - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
          - git clone https://github.com/eellak/gsoc2019-NextCloudPi.git
          - cd gsoc2019-NextCloudPi
          - git checkout gsoc2019-travis
         
          script:
          - sed -i "s/create_torrent/#create_torrent/" build-SD-rpi.sh
          - sed -i "s/upload_ftp/#upload_ftp/" build-SD-rpi.sh
          - while sleep 9m; do echo "=====[ $SECONDS seconds, still building rpi image... ]====="; done &
          - ./build-SD-rpi.sh > f_output

notifications:
  email: false
