sudo: required
language: generic
dist: xenial
jobs:
  include:
        - stage: building_images
          script:
          - ./.travis/configure_docker.sh
          - export DOCKER_CLI_EXPERIMENTAL=enabled #enable experimental features
            # - wget -O- http://travis.debian.net/script.sh | sh -
          - git clone https://github.com/eellak/gsoc2019-NextCloudPi.git
            #          - cd gsoc2019-NextCloudPi
            #          - 
          - cat /etc/os-release
notifications:
        email: false
