sudo: required
language: generic
services:
        - docker
before_script:
        - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
script:
        - sudo ls /proc/sys/fs/binfmt_misc/
        - ./run.sh
        
