sudo: required
language: generic
addons:
  apt:
    packages:
      - docker-ce
services:
        - docker
before_script:
        - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
        - sudo apt-get update && sudo apt-get install -y realpath bc
script:
        - sudo cat /proc/sys/fs/binfmt_misc/qemu-arm
        - ./run.sh
        - docker version
        - sudo cat /etc/docker/daemon.json
        
