stages:
        - building_images
        - deploy
sudo: required
language: generic
dist: xenial
before_script:
        - ./.travis/main.sh #configuration script for travis machine
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - docker version
jobs:
  include:
        - stage: building_images
          script: ./build-SD-rpi.sh

        - stage: deploy
          script: ls        
notifications:
        email: false

