sudo: required
language: generic
dist: xenial
addons:
  apt:
     sources:
        - debian-sid
jobs:
  include:
        - stage: building_images
          script:
          - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static 
            # - wget -O- http://travis.debian.net/script.sh | sh -
          - git clone https://github.com/eellak/gsoc2019-NextCloudPi.git
          - cd gsoc2019-NextCloudPi
          - git checkout gsoc2019-travis
            #- sed -i "s/create_torrent/#create_torrent/" build-SD-rpi.sh
            #- sed -i "s/upload_ftp/#upload_ftp/" build-SD-rpi.sh
            #- while sleep 9m; do echo "=====[ $SECONDS seconds, still building rpi image... ]====="; done &
            #- ./build-SD-rpi.sh

          - curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | sudo bash
notifications:
        email: false
