stages:
        - configuration
        - build_debian-ncp
        - build_lamp
        - build_nc
        - build_ncp
sudo: required
language: generic
addons:
  apt:
    packages:
        - docker-ce #Upgrade Docker to 18.06 version that supports experimental features
services:
        - docker
env:
        - TEST_SUITE="touch new"
        - TEST_SUITE="ls ."
before_script:
        - ./.travis/main.sh #configuration script for travis machine
jobs:
   include:
        - stage: configuration
          env: null
          script: 
                - touch Hello

        - stage: build_debian-ncp
          before_script: true
          script: 
                - printenv | grep DOCKER
