sudo: required
language: generic
services:
        - docker
before_install:
        - sudo apt-get install qemu-user-binfmt
script:
        - sudo ls /proc/sys/fs/binfmt_misc/
        - ./run.sh
        
