stages:
        - configuration
        - build_debian-ncp
        - build_lamp
        - build_nc
        - build_ncp
sudo: required
language: generic
addons:
  apt:
    packages:
        - docker-ce #Upgrade Docker to 18.06 version that supports experimental features
services:
        - docker
cache:
    directories:
        - /var/lib/docker
before_script:
        - ./.travis/main.sh
jobs:
   include:
        - stage: build_debian-ncp
          script: DOCKER_BUILDKIT=1 docker build . -f docker/debian-ncp/Dockerfile -t ownyourbits/debian-ncp-amd64:latest --pull --build-arg arch=amd64 --build-arg arch_qemu=x86_64
        -
          script: ./testit.sh
