stages:
        - building_images
        - deploy
sudo: required
language: generic
dist: xenial
jobs:
  include:
        - stage: building_images
          script:
           - IP=$(ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')
        - stage: deploy
          before_script:
          - echo "hello world"
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          script: ls .
notifications:
        email: false
