stages:
        - building
sudo: required
language: generic
dist: xenial
jobs:
  include:
        - stage: building
          env:
              JOB1
          install:
          - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
          - sudo ls /etc/ | grep php
          - sudo ls /usr/bin/locale
          - sudo ls /usr/bin | grep locale
          - sudo apt-get purge locales
          - sudo aptitude install locales

          - sudo locale-gen en_US.UTF-8
          - export LANGUAGE="en_US.UTF-8"
          - export LANG="en_US.UTF-8"
          - export LC_ALL="en_US.UTF-8"
          - export LC_CTYPE="en_US.UTF-8"
            #a- sudo dpkg-reconfigure locales
            ###################
            #          - sudo dpkg-reconfigure locales # add the en_GB.UTF-8 locale and set as default
            #          - export LANGUAGE=en_US.UTF-8 
            #          - export LANG=en_US.UTF-8
            #          - export LC_ALL=en_US.UTF-8
            #          - sudo locale-gen en_US.UTF-8
            #          - sudo update-locale en_US.UTF-8

            #          - locale

            #          - sudo cat /etc/locale.gen
            #          - sudo cat /etc/default/locale
            #          - sudo sed -i "" /etc/local.gen
          script:
          - git clone https://github.com/eellak/gsoc2019-NextCloudPi.git
          - git checkout gsoc2019-travis
          - cd gsoc2019-NextCloudPi
          - sed -i "s/create_torrent/#create_torrent/" build-SD-rpi.sh
          - sed -i "s/upload_ftp/#upload_ftp/" build-SD-rpi.sh
          - sed -i "/innodb_file_format=barracuda/a open_files_limit=65536" lamp.sh
          - while sleep 9m; do echo "=====[ $SECONDS seconds, still building rpi image... ]====="; done &
            #- tail -f f_out &
          - bash -x ./build-SD-rpi.sh
        -         
          env:
              JOB2
          script:  
          - git clone https://github.com/eellak/gsoc2019-NextCloudPi.git
          - git checkout gsoc2019-travis
          - cd gsoc2019-NextCloudPi
          - sed -i "s/create_torrent/#create_torrent/" build-SD-armbian.sh
          - sed -i "s/upload_ftp/#upload_ftp/" build-SD-armbian.sh
          - sed -i "/innodb_file_format=barracuda/a open_files_limit=65536" lamp.sh
          - while sleep 9m; do echo "=====[ $SECONDS seconds, still building armbian image... ]====="; done &
            #- tail -f f_output &
          - bash -x ./build-SD-armbian.sh odroidxu4 OdroidHC2 #> f_output
          
notifications:
  email: false
