stages:
        - building_images
        - deploy
sudo: required
language: generic
dist: xenial
jobs:
  include:
        - stage: building_images
          script: ./batch.sh
notifications:
        email: false
