stages:
        - building_images
        - deploy
sudo: required
language: generic
dist: xenial
before_script:
        - ./.travis/main.sh #configuration script for travis machine
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - docker version
jobs:
  include:
        - stage: building_images
          script:
            - DOCKER_BUILDKIT=1 docker build . -f docker/debian-ncp/Dockerfile -t ownyourbits/debian-ncp-amd64:latest --pull --build-arg arch=amd64 --build-arg arch_qemu=x86_64 > output & tail -f output
        -
          script: DOCKER_BUILDKIT=1 docker build . -f docker/debian-ncp/Dockerfile -t ownyourbits/debian-ncp-armhf:latest --pull --build-arg arch=armhf --build-arg arch_qemu=arm > output & tail -f output

        - stage: deploy
          script: ls       
notifications:
        email: false

