stages:
        - build_1
        - build_2
sudo: required
language: generic
addons:
  apt:
    packages:
        - docker-ce #Upgrade Docker to 18.06 version that supports experimental features
services:
        - docker
cache: ccache
before_script:
        - ./.travis/main.sh
        - export DOCKER_CLI_EXPERIMENTAL=enabled
jobs:
   include:
        - stage: build_1
          script:
                  - printenv | grep DOCKER
                  - DOCKER_BUILDKIT=1 docker build . -f docker/debian-ncp/Dockerfile -t ownyourbits/debian-ncp-amd64:latest --pull --build-arg arch=amd64 --build-arg arch_qemu=x86_64
                  - docker images
                  - printenv | grep DOCKER
                  - DOCKER_BUILDKIT=1 docker build . -f docker/lamp/Dockerfile -t ownyourbits/lamp-amd64:latest --pull --build-arg arch=amd64
        - stage: build_2
          script:
                  - printenv | grep DOCKER
                  - docker images
