stages:
        - configuration
        - build_debian-ncp
        - build_lamp
        - build_nc
        - build_ncp
sudo: required
language: generic
addons:
  apt:
    packages:
        - docker-ce #Upgrade Docker to 18.06 version that supports experimental features
services:
        - docker
cache:
    directories:
        - /var/lib/docker
          #env:
          #        - TEST_SUITE="testit.sh"
          #        - TEST_SUITE="testit2.sh"
before_script:
        - ./.travis/main.sh #configuration script for travis machine
jobs:
   include:
        - stage: configuration
          env: null
          script: 
                - touch Hello
                - docker pull hello-world

        - &build_debian-ncp
          stage: build_debian-ncp
          script: 
                - ./testit.sh
                -
                - ./testit2.sh
