sudo: required
language: generic
addons:
  apt:
    packages:
      - docker-ce
services:
        - docker
before_script:
        - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
        - sudo jq '/etc/docker/daemon.json += [{"experimental": "true"}]'
        - docker restart
script:
        - ./run.sh
        - docker version
        - sudo cat /etc/docker/daemon.json
        
