stages:
        - building
sudo: required
language: generic
dist: xenial
jobs:
  include:
        - stage: building

          install:
          - sudo apt-get update -q
          - sudo apt-get install -q virtualbox --fix-missing
          - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
          - sudo dpkg -i vagrant_1.7.2_x86_64.deb
          - bundle install

          script:
          - vagrant up
          - curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash

notifications:
  email: false
