stages:
        - building
sudo: required
language: generic
dist: xenial
jobs:
  include:
        - stage: building

          install:
          - sudo apt-get install vagrant
          - sudo apt-get install -q virtualbox --fix-missing

          script:
          - vagrant up
          - curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash

notifications:
  email: false
